spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/blog
    username: root
    password:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    pool:
      max-active: 8  # 连接池最大连接数（使用负值表示没有限制）
      max-idle: -1   # 连接池中的最大空闲连接
      max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制）
      min-idle: 0 # 连接池中的最小空闲连接
    timeout: 0 # 连接超时时间（毫秒）
# mybatis:
#  type-aliases-package: com.mrc.domain
#  mapper-locations: classpath:mapper/*.xml
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



